# Generated by Django 3.2.2 on 2021-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='tagline',
            field=models.CharField(max_length=25),
        ),
    ]
