# Generated by Django 3.2.2 on 2021-05-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_info_skills_8_csv_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='skills_8_csv_values',
        ),
    ]
