# Generated by Django 3.2.2 on 2021-05-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_info_skills_8_csv_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('short_desc', models.CharField(max_length=50)),
                ('long_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
