# Generated by Django 3.2.2 on 2021-05-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='long_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
