# Generated by Django 3.2.2 on 2021-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210511_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='more',
            name='tenure',
        ),
        migrations.AddField(
            model_name='more',
            name='secondary_desc',
            field=models.CharField(default='Hello', max_length=50),
            preserve_default=False,
        ),
    ]
