# Generated by Django 3.2 on 2021-05-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20210511_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(default='abhaychirania2411@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='github',
            field=models.CharField(default=-7358519252, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='instagram',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='linkedin',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='phone',
            field=models.CharField(default='a', max_length=15),
            preserve_default=False,
        ),
    ]
