# Generated by Django 3.2 on 2021-05-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20210512_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='github',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='info',
            name='linkedin',
            field=models.CharField(max_length=80),
        ),
    ]
